### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by LFS6502** [cracker64/tptmp#20] opened 2019-08-26 01:41 UTC
Upon starting the game, the following error is displayed:
multiplayer.lua2006: bad argument #2 to 'unregister' (function expected, got nil)

This is a persistent issue.

**Comment by jacob1** [comment] 2019-08-26 01:44
This is a legitimate issue, no reason to close it. It's probably happening because you have two tptmps installed.

When you have two versions, it tries to replace the old one with the new one. That function is broken.

**Comment by LFS6502** [comment] 2019-08-26 01:44
It turns out that the script manager was outdated, and the update fixed it.

**Comment by jacob1** [comment] 2019-08-26 01:46
That's good. I'll still try to fix that broken function.

Weird that updating script manager is what fixed it.

Are you by any chance using my mod? If so, uninstalling tptmp in the script manager would be a good workaround for this issue.

**Comment by LFS6502** [comment] 2019-08-26 01:47
I am actually not the user having this issue, but rather a friend of mine. I just informed him, and he should be able to provide you with more information.

**Comment by jacob1** [comment] 2019-08-26 01:48
ok. More information isn't necessary to fix it, since I can easily reproduce it myself by typing TPTMP.disableMultiplayer() in the console.

**Comment by soweli-Luna** [comment] 2019-08-26 01:49
Yes, thats me. I am using your mod, the issue seems to be resolved after updating the script manager, I'll let you know if it happens again.

**Comment by jacob1** [comment] 2020-12-08 16:23
Fixed in 67bc0f3fe1d028a98ee772760af96e4112972de5

**Closed as completed by jacob1** 2020-12-08 16:23 UTC
